### ISSUE TITLE
Scheduling posts for longer than 24 days out will cause it to get stuck in a loop

### ISSUE THREAD

**Issue by bradvogel** [jsantell/poet#119]
V8 has a known issue where if you pass a number larger than 2^31 to setTimeout, it will fire immediately. So line https://github.com/jsantell/poet/blob/master/lib/poet/methods.js#L187 will get stuck in a loop calling poet#init if it sees a post that's scheduled more than 2^31 (24.8 days) out.

http://stackoverflow.com/questions/16314750/settimeout-fires-immediately-if-the-delay-more-than-2147483648-milliseconds

**Comment by bradvogel** [comment]
Is this project still accepting PRs?

**Comment by jsantell** [comment]
Nice find! I'll check out #120 later today

**Comment by ChrisMcKenzie** [comment]
This has landed in jsantell/poet@2.0.2
