### ISSUE TITLE
Watcher should fire when a post date becomes current

### ISSUE THREAD

**Issue by Darkhogg** [jsantell/poet#66]
As of now, posts cannot be scheduled, as an explicit modification on a file must happen in order for the watcher to fire.

When a post is loaded with a future date and `showFuture` is `false`, watch should be scheduled to fire as if the future post was edited at its date so Poet reloads it and adds it as a current post.

This would allow post scheduling, currently only available if done manually or with added code.

**Comment by bradvogel** [comment]
@jsantell Would you mind pushing a new version to NPM with this fix?

**Comment by jsantell** [comment]
Probably could use a new release on npm, it's been awhile -- @ChrisMcKenzie is this something you can take care of? I might be able to get around to it next week

**Comment by ChrisMcKenzie** [comment]
I will do it tonight!

**Comment by bradvogel** [comment]
:+1:

**Comment by ChrisMcKenzie** [comment]
@jsantell I must admit kind of a newb to publish on npm it would seem I cannot publish but everything is ready. I'm not sure if access to the registry can be granted?

**Comment by jsantell** [comment]
@ChrisMcKenzie what's your npm name? I'll give you access there

**Comment by ChrisMcKenzie** [comment]
oh cool! it's just `chrismckenzie`

**Comment by jsantell** [comment]
npm owner add chrismckenzie poet
+ chrismckenzie (poet)

should be good to go!

**Comment by jsantell** [comment]
@ChrisMcKenzie ^

**Comment by ChrisMcKenzie** [comment]
sweet man thanks!

**Comment by bradvogel** [comment]
Thanks!
